baseURL = 'https://mfa-labs.github.io/course-materials/'
languageCode = 'en-us'

title = "Course Materials"
theme = "hugo-book"

contentDir = "content"
defaultContentLanguage = "en"
enableRobotsTXT = true

[params]
  github_repo = "https://github.com/mfa-labs/course-materials"
  github_branch = "main"

[menu]